#!/bin/bash
KEY="$HOME/.key/securecrt"


env_build(){
ssh-agent 
ssh-add $KEY
}
env_install(){
if [ ! -d $HOME/.key ];then
	mkdir $HOME/.key
fi
cat << EOF > $KEY
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,87B0AB8C75F3ADD2

lYXnfVNENnXeuCvJ24W43U+EpL8eRWHyiqTZUxB891gsY4+BaN5b9Y3NHBpvEPfE
p7bbGg1x4MR8/dOfQQNf0ggzf8yPd5jdRb48Ri4vptP2WjT72iYN4z2wx731kQeu
a1YFd96rSPbLvmflHQReNwcdFDDlFYFjQerGCH9LHEgUlFjWtS+4gWuLZmFPf1ku
jY71Qa07qGn8mID0oQi0Eai7XtMUhUfVY4+iJWO6cVw+bTBkF8janLKNGybmW4uW
PcCXYkRVzXbmpjecUM64bHGHadWeoOnk3WS/pA2IYUtagLxLPWGcvvU6NZsi9zpz
IsUD7kiMftYFW6InXRjPR/2xHEwjmvEPFy7treyBV7aTEs33daz3cEDQQnifD1q2
YniEv3PceHiN0qEMtRuQCnSKqoEXfK2kYvPdf1xFDmWMDOQfwxSXmMenIaDZ3Ur7
Ur9xEEGv7DpS+csnSVU2FnCp0V58ZoYErlrTybGG94Ol/yU5IK+SkUEQLCEZgKMz
WDXrGaRVeE0RqJZNGhiOMLj9Xo8G3jlEO25u6crBJTXsjz/jgL5+hu37jAleWgQp
mS3TFQxCjvPXQEyuHfSeI+txdqYEU2PzT1yldyWU4aiW/9ZYOQ3HeOiOa11JnQ6K
alXYlRgLQKUUVNMrCrUnVHQbevyP2Wu/uXxrFVs3UUdSJgZInwkNEoi1ASoLRhWT
Vee7Bt/es4SC7bxV9N0dfCjivH5N9cx3wyyy6L+Tn7cJYkOeSMnyKQCPSEV/oWQk
w6OoeVbXZMGsP8pvaljn1/r6WUS8I0cFKeT1qa0/iet2ZlId0ZX9jH/GOZQxE281
QARr0oeV/CRIEo0TMKkok0hC8X0Ud0sFNXXeuWqUKRJpHTLqpDLyTw899LL+z52B
kqlsceGMgaHzVr5iaGC9ZF0ue89x2JmL3GElHnRmxJARUdLmBxrsKhOkoerI+HvD
ZUdgDbmzcQQWPC/M4tuw2RPv04dqRDta69FcrPUfXtCMYasgu3MPtlhM3IOqoMxI
+xfl8kzow7kiB9CjUNI0dN0eDLljYGtvySr/rTLvgtpWUaaidM9wtCpJPaDcD8Nh
uD4LpVwbVztnS98oN/2SLpBB6QEjKfZ+PgZrnZIJGrpBev/ZBTTWSyeFFQvXnZWE
Q6Dc8aJUNP0+cTpsjiCTNUKl0OmN4udWz+0iqd4kb+4oPEOf5vLBpfqo1CA5yyRt
GIIIcOmDnjbefjTJrfRqVYHUrIq6Rs7Fxg2e5vh+LjXIGJcmit/ZwV2dLaPolkpT
NTOMzLnuO27kzlRiDWAW1Z0SoxaH7ZQt3Ko6GjWkCLGZQHAjWGg3aWMchybu3CA/
VGw2j9qfdvSNP5R8qKwDjBWo77KdY0t6jL1MQmE4qnGJv0WUaYDDcRCbkC1Rzsvd
dd8fYQjn7JTw3D36ReRngaj8364J/3M12nbNXS5EwlRbWMeaY93blYUXfFwSfDew
2gZ09YjKnWHmmko5nfKtOCKk6lt+vXbT9k+yjRn/wlKeSS+XG+ss+gLxvMVF9O2X
gCOn5BxpNDHpzBzlBDo7KXe2AT4kUeIKpBvZIbAor365X6OshC/xTXIcUTak8/cc
yHR/HxM/Cn4pCfqAK3E3h6aiydkGa6ChRHlUYHb4bEMIPrkUmfb0vhGlmQTsiFZE
v/SzTW9gdFakDWRhuuAVyPM7WsicMXGa3BVVc/ZBOudNIsmvDooYP7x2cKHnpgXP
uwAnhiHbMRRSf0vDIBq2kFHp/UlGYutEwMPKjNAMOc1sWLvhbNLpa7cNJQxYeGW/
3CYSqfuYr9iou9d9QcJmQ3cZpTrU6fQcGZy1NKyeU+xVAW3BQCYeGIQ82nPJX9aS
CUVeS9FpORZPdYoLvK/oLoDNrdMeYUS0HQPpUYultQFBHkahpVfViyVIlymfq8/l
pi2uMIn3jPPlXqLGgqipjnJc9vi1XOiB8EDSUGOzuSMQ1aMzfOOBDaEnX3xpoHai
S5ZEpufAZxE+B3L0feDldX3TFAn9h0ph5qsAIAItOs8OgeEcohc6snYL2gFbowWK
OlYso/CoW0ePloYujTWMs6OdzVa5iE51gQp9C/n/jtN6/UNqrnjspAMN1IzPYxpa
dDf4OMGs3UAOaTu0Om20kC9wGRRN3jQ48LZO+3Vsa18hMABwZl/8ajuFf7YEnxvu
mwQRv5wum9dDBhtnVE2AaEdU5fY+RjXVBOI9yrjj6e/geUEcviJNZc7XR7di57uR
TL/W4is73qW4ZA5QtnpwxJ/hvuQVDD3Ijp4ovN93my4cVhh39EYmSXNF0KokGijr
4RUArHaP0aL1MIPfKeFkS0CPZS9VtaCPwk44ZJA1kV7VNjU/cgNZZn4qYk416h4s
AXm38aRb4HF+NPHMgBxG1sI1HkQIJl2odjBpcEYrEiZEQlk56Zb241ZG4IZNf8i3
JL0v0PbQr911X27Hra+bItvf6kHIzWiEiyMwNK27I29WD+ZAIYkhKrlTjHeFzkwD
SJy/Rm30tZrc+WDRH/MBacsGSX4Gwy8mQtWtQoF/JRaGVKvjvicn7CZgffyXc0fz
nEWZ1ZcUFRw4h+JoSnSA2ZWn+Fmysj/Q/6pqKrxv5nIOCfSF3W4UP+7I0cu14Urv
PHdEBnyZ4ljOMJSbRJkqoR7qhkJnj8PT5ci3ZMHj1Lnm2B9EoplUR8/ZbGQH8PXa
66n5k8DbarUJV8BpWnJfl7si3lcE3DewBpDtTFu4wXntf0TaLzY4CIwwnDR6ooIL
T1Fwzk70+l45jres5feNV3DvgitsxCc6YLiuM9usamicBr2Q20CpbuCFjh5gYk3r
fcYN7wm5719jUhfXbWl39/pB4vIAz5i/tbuSGdqW2NVvlmI26MtVq8M6LwSqcgR4
zdmhiMzRGFQqu9uZey8V1HvEuHfDUGTTGTe/jw1sb23xVU2mTZZjUzhjdfMBMF+I
ILiCCI+ttjuveBHsmnK01d+RIQ/Cf5cr1OkYK+5fTb+xU9wACbjt8T/SIuaDxD2o
mbJUG4robss6nCfDIbZw0NtI//eWG00FHfrEtsnAjU8ht5mYePrhXD3Y8ITkBNDX
AhrGj3p5lQ1lPFiJmDivSjOpFSgA/bgshheAn1rDZ8r/2rCDFr4osBHOa+74bv3O
-----END RSA PRIVATE KEY-----
EOF
chmod 600 $KEY
}

case $1 in
	host)
		if [ -z $2 ];then
			echo "please input ip:port string!"
		else
			host=$(echo "$2"|awk -F: '{print $1}')
			port=$(echo "$2"|awk -F: '{print $2}')
			user=$(echo "$2"|awk -F: '{print $3}')
			if [ -z $user ];then
				if [ -z $port ];then
					ssh root@$host
				else
					ssh -p $port root@$host
				fi
			else
				if [ -z $port ];then
					ssh $user@$host
				else
					ssh -p $port $user@$host
				fi
			fi
		fi
		;;
	agent)
		env_build
		;;
	install)
		env_install
		;;
	*)
		echo "Usage:$0 (host ip:port:user|agent|install)"
		;;
esac
